name: Publish Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: Release
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v3

      - name: Set node version to 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
          cache: pnpm

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Create Release And Tag
        id: changesets
        uses: changesets/action@v1
        with:
          publish: npx @changesets/cli tag
          commit: 'release: :rocket: release version'
          title: 'release: release version'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
